stages:
  - tests
  - deploy_analyse

image:
  finanzcheck/docker-node-java:latest

unit-test:
  stage: tests
  before_script:
  - npm install jest
  script:
  - npm test

sonar:
  stage: deploy_analyse
  before_script:
    - npm install sonar-scanner@3.1.0
  script:
    - npm run sonar-scanner -- -Dsonar.host.url=https://sonarcloud.io -Dsonar.projectKey=cdp:cdp -Dsonar.organization=apodeus-github -Dsonar.sources=src -Dsonar.plsql.version=5.6 -Dsonar.branch.name=$CI_COMMIT_REF_NAME -Dsonar.login=$SONAR_TOKEN

docker-img:
    stage: deploy_analyse
    services:
    - docker:dind

    before_script:
    - docker info
    - apk update
    - apk upgrade
    - apk add python python-dev py-pip build-base
    - pip install docker-compose

    image: docker:latest
    script:
    - docker-compose up --no-start
    after_script:
    - docker-compose down
