stages:
  - analyse

image:
   node:latest

sonar:
  stage: analyse
  services:
    - java:latest
  before_script:
    - npm install sonar-scanner@3.1.0
  script:
    - ls
    - npm run sonar-scanner -s settings.xml
