sudo: required
addons:
  apt:
    packages:
      - docker-ce

services:
        - docker

language: 
        - node_js
node_js:
        - "iojs"
        - "7"
before_install:
        - sudo /etc/init.d/mysql stop
        - sudo docker-compose up -d
        - docker --version
        - npm i selenium-webdriver

script :
        - echo "Waiting selenium server"
        - sleep 15
        - curl localhost:3000
        - npm install nightwatch
        - echo "Start of E2E Tests"
        - ./node_modules/nightwatch/bin/nightwatch -t src/test/e2e.js
