sudo: required
addons:
  apt:
    packages:
      - docker-ce

services:
        - docker


language: 
        - python
        - node_js
python:
        - "3.3"
node_js:
        - "iojs"
        - "7"
before_install:
        - sudo /etc/init.d/mysql stop
        - pwd
        - ls -la
        - sudo docker-compose up -d
        - docker --version
        - pip install selenium

script :
        - echo "Waiting selenium server"
        - sleep 20
        - curl localhost:3000
        - npm install nightwatch
        - echo "Start of E2E Tests"
        - ./node_modules/nightwatch/bin/nightwatch -t src/test/e2e.js
