sudo: required
addons:
  apt:
    packages:
      - docker-ce

services:
        - docker


language: 
        - python
        - node_js
python:
        - "3.3"
node_js:
        - "iojs"
        - "7"
before_install:
        - sudo /etc/init.d/mysql stop
        - pwd
        - ls -la
        - sudo docker-compose up -d
        - docker --version
        - npm install puppeteer
	- npm install jest
	- npm install jest-sonar-reporter

script :
        - echo "Waiting stuff"
        - sleep 20
        - curl localhost:3000
        - echo "Start of E2E Tests"
        - npm test -- src/test/e2e
