version: "2.1"
services:
  app:
    container_name: app
    restart: always
    build: .
    ports:
      - "3000:3000"
    links:
      - "database"
  database:
    container_name: database
    image: mysql:5.6
    expose:
    - "3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cdp
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_RANDOM_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: root
    volumes:
      - ./data:/data/db
    ports:
      - "3306:3306"
  adminer:
    container_name: adminer
    image: adminer
    restart: always
    ports:
      - "8080:8080"