DROP TABLE IF EXISTS users;

CREATE TABLE users(
  id INTEGER NOT NULL auto_increment PRIMARY KEY ,
  pseudo VARCHAR(20) NOT NULL,
  email VARCHAR(60) NOT NULL,
  password VARCHAR(20) NOT NULL
)ENGINE=InnoDB;
